import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useEnrollmentStore } from '../../stores/enrollmentStore';
import { useAuthStore } from '../../stores/authStore';
import { EnrollmentStatus } from '@mos/shared';
export function StudentDashboardPage() {
    const { user } = useAuthStore();
    const { enrollments, isLoading, fetchMyEnrollments } = useEnrollmentStore();
    useEffect(() => {
        fetchMyEnrollments();
    }, []);
    const active = enrollments.filter((e) => e.status === EnrollmentStatus.ACTIVE);
    const completed = enrollments.filter((e) => e.status === EnrollmentStatus.COMPLETED);
    const avgProgress = active.length > 0 ? active.reduce((s, e) => s + e.progress, 0) / active.length : 0;
    return (_jsxs("div", { className: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12", children: [_jsxs("div", { className: "page-header", children: [_jsxs("h1", { className: "page-title", children: ["Welcome back, ", user?.firstName, "! \uD83D\uDC4B"] }), _jsx("p", { className: "page-subtitle", children: "Track your progress and continue learning" })] }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-3 gap-6 mb-10 animate-fade-in-up", style: { animationDelay: '100ms', opacity: 0 }, children: [_jsxs("div", { className: "stat-card", children: [_jsx("div", { className: "text-slate-400 text-sm", children: "Active Courses" }), _jsx("div", { className: "text-4xl font-black text-white", children: active.length })] }), _jsxs("div", { className: "stat-card", children: [_jsx("div", { className: "text-slate-400 text-sm", children: "Completed" }), _jsx("div", { className: "text-4xl font-black text-emerald-400", children: completed.length })] }), _jsxs("div", { className: "stat-card", children: [_jsx("div", { className: "text-slate-400 text-sm", children: "Avg Progress" }), _jsxs("div", { className: "text-4xl font-black text-brand-400", children: [Math.round(avgProgress), "%"] })] })] }), _jsx("h2", { className: "text-xl font-semibold text-white mb-6", children: "My Courses" }), isLoading ? (_jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6", children: [1, 2, 3].map((i) => (_jsxs("div", { className: "card animate-pulse", children: [_jsx("div", { className: "h-4 bg-slate-800 rounded mb-3 w-3/4" }), _jsx("div", { className: "h-3 bg-slate-800 rounded mb-6 w-1/2" }), _jsx("div", { className: "h-2 bg-slate-800 rounded" })] }, i))) })) : enrollments.length === 0 ? (_jsxs("div", { className: "text-center py-20 text-slate-400", children: [_jsx("div", { className: "text-5xl mb-4", children: "\uD83C\uDF93" }), _jsx("p", { className: "text-lg", children: "No enrollments yet" }), _jsx(Link, { to: "/courses", className: "btn-primary mt-4 inline-block", children: "Browse courses" })] })) : (_jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6", children: enrollments.map((enrollment, idx) => (_jsxs("div", { className: "card flex flex-col gap-4 animate-fade-in-up", style: { animationDelay: `${200 + idx * 100}ms`, opacity: 0 }, children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-white line-clamp-2", children: enrollment.course?.title || 'Course' }), _jsx("p", { className: "text-xs text-slate-500 mt-1", children: enrollment.course?.examCode })] }), _jsx("span", { className: enrollment.status === EnrollmentStatus.COMPLETED
                                        ? 'badge-green'
                                        : enrollment.status === EnrollmentStatus.DROPPED
                                            ? 'badge-red'
                                            : 'badge-blue', children: enrollment.status })] }), _jsxs("div", { children: [_jsxs("div", { className: "flex justify-between text-xs text-slate-400 mb-1.5", children: [_jsx("span", { children: "Progress" }), _jsxs("span", { children: [Math.round(enrollment.progress), "%"] })] }), _jsx("div", { className: "h-2 rounded-full bg-slate-800 overflow-hidden", children: _jsx("div", { className: "h-full rounded-full bg-gradient-to-r from-brand-600 to-brand-400 transition-all duration-500", style: { width: `${enrollment.progress}%` } }) })] }), _jsxs("div", { className: "flex gap-2 mt-2", children: [_jsxs(Link, { to: `/courses/${enrollment.courseId}/learn`, id: `continue-${enrollment.courseId}`, className: "btn-secondary text-center text-sm flex-1", children: [enrollment.status === EnrollmentStatus.COMPLETED ? 'Review' : 'Continue', " \u2192"] }), enrollment.status === EnrollmentStatus.COMPLETED && (_jsx(Link, { to: `/certificate/${enrollment.id}`, className: "btn-primary bg-yellow-600 hover:bg-yellow-500 shadow-yellow-500/20 shadow-lg text-center text-sm flex-1", children: "\uD83C\uDFC6 Certificate" }))] })] }, enrollment.id))) }))] }));
}
//# sourceMappingURL=StudentDashboardPage.js.map