import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Outlet, Link, useNavigate } from 'react-router-dom';
import { useAuthStore } from '../../stores/authStore';
import { UserRole } from '@mos/shared';
export function AppLayout() {
    const { user, logout } = useAuthStore();
    const navigate = useNavigate();
    const handleLogout = async () => {
        await logout();
        navigate('/auth/login');
    };
    return (_jsxs("div", { className: "min-h-screen flex flex-col", children: [_jsx("nav", { className: "sticky top-0 z-50 border-b border-slate-800 bg-slate-950/80 backdrop-blur-md", children: _jsx("div", { className: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex h-16 items-center justify-between", children: [_jsxs(Link, { to: "/courses", className: "flex items-center gap-2", children: [_jsx("div", { className: "h-8 w-8 rounded-lg bg-gradient-to-br from-brand-500 to-brand-700 flex items-center justify-center text-white font-bold text-sm", children: "N" }), _jsx("span", { className: "font-bold text-white text-lg", children: "Najdawi Platform" })] }), _jsxs("div", { className: "flex items-center gap-6", children: [_jsx(Link, { to: "/courses", className: "text-sm text-slate-400 hover:text-white transition-colors", children: "Courses" }), user && (_jsx(Link, { to: "/student/dashboard", className: "text-sm text-slate-400 hover:text-white transition-colors", children: "My Learning" })), (user?.role === UserRole.ADMIN || user?.role === UserRole.INSTRUCTOR) && (_jsx(Link, { to: "/admin/dashboard", className: "text-sm text-slate-400 hover:text-white transition-colors", children: user.role === UserRole.ADMIN ? 'Admin' : 'Instructor Dashboard' }))] }), _jsx("div", { className: "flex items-center gap-3", children: user ? (_jsxs(_Fragment, { children: [_jsxs("div", { className: "flex items-center gap-2 px-3 py-1.5 rounded-full bg-slate-800 border border-slate-700", children: [_jsx("div", { className: "h-6 w-6 rounded-full bg-brand-600 flex items-center justify-center text-xs font-bold text-white", children: user.firstName[0] }), _jsx("span", { className: "text-sm text-slate-300 hidden sm:block", children: user.firstName })] }), _jsx("button", { id: "logout-btn", onClick: handleLogout, className: "btn-secondary text-xs px-3 py-1.5", children: "Sign out" })] })) : (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/auth/login", className: "btn-secondary text-xs px-4 py-2", children: "Sign in" }), _jsx(Link, { to: "/auth/register", className: "btn-primary text-xs px-4 py-2", children: "Get started" })] })) })] }) }) }), _jsx("main", { className: "flex-1", children: _jsx(Outlet, {}) }), _jsx("footer", { className: "border-t border-slate-800 py-8 mt-16", children: _jsxs("div", { className: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center text-slate-500 text-sm", children: ["\u00A9 ", new Date().getFullYear(), " Najdawi Platform. All rights reserved."] }) })] }));
}
//# sourceMappingURL=AppLayout.js.map